export enum Events {
    RUN_MEASUREMENT = "RUN_MEASUREMENT",
    GET_BASIC_NETWORK_INFO = "GET_BASIC_NETWORK_INFO",
    GET_MEASUREMENT_STATE = "GET_MEASUREMENT_STATE",
    GET_MEASUREMENT_RESULT = "GET_MEASUREMENT_RESULT",
    ERROR = "ERROR",
}
