export enum Events {
    RUN_MEASUREMENT = "RUN_MEASUREMENT",
    GET_INIT_STATE = "GET_INIT_STATE",
    GET_PRE_DOWNLOAD_STATE = "GET_PRE_DOWNLOAD_STATE",
    GET_PING_STATE = "GET_PING_STATE",
    GET_DOWNLOAD_STATE = "GET_DOWNLOAD_STATE",
    GET_PRE_UPLOAD_STATE = "GET_PRE_UPLOAD_STATE",
    GET_UPLOAD_STATE = "GET_UPLOAD_STATE",
    MEASUREMENT_FINISH = "MEASUREMENT_FINISH",
}
