export enum Events {
    REGISTER_CLIENT = "REGISTER_CLIENT",
    RUN_MEASUREMENT = "RUN_MEASUREMENT",
    ABORT_MEASUREMENT = "ABORT_MESUREMENT",
    GET_ENV = "GET_ENV",
    GET_CPU_USAGE = "GET_CPU_USAGE",
    GET_MEASUREMENT_STATE = "GET_MEASUREMENT_STATE",
    GET_MEASUREMENT_RESULT = "GET_MEASUREMENT_RESULT",
    ERROR = "ERROR",
}
