export enum ERoutes {
    CERTIFIED = "certified",
    CLIENT = "client",
    HELP = "help",
    HISTORY = "history",
    LOOP_MODE = "loop",
    LOOP_TEST = "loop-test",
    LOOP_RESULT = "loop-result/:loopUuid",
    MAP = "map",
    NEWS = "new",
    SETTINGS = "settings",
    STATISTICS = "statistics",
    TERMS_CONDITIONS = "terms-conditions",
    TEST = "test",
    TEST_RESULT = "result/:testUuid",
}
