name: Build Linux apps

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Get .env
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        curl -H "Authorization: token $REPO_TOKEN" -H "Accept: application/vnd.github.v3.raw" -o .env -L https://api.github.com/repos/rtr-nettest/open-rmbt-desktop-private/contents/.env.windows-ci
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Build
      run: |
        sudo apt-get install -y rpm
        npm install
        cd src
        cd ui
        npm install
        cd ..
        cd ..
        npm run make:deb
        npm run make:rpm
    - uses: actions/upload-artifact@v3
      with:
        name: application-rpm
        path: out/make/rpm/x64/*.rpm
    - uses: actions/upload-artifact@v3
      with:
        name: application-deb
        path: out/make/deb/x64/*.deb
        
