name: Build mac os app

on:
  push:
    
jobs:
  build:
    runs-on: macos-12     
    steps:
    - uses: actions/checkout@v3
    - name: Get .env
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        curl -H "Authorization: token $REPO_TOKEN" -H "Accept: application/vnd.github.v3.raw" -o .env -L https://api.github.com/repos/rtr-nettest/open-rmbt-desktop-private/contents/.env.windows-ci
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Build
      run: |
        npm install
        cd src
        cd ui
        npm install
        cd ..
        cd ..
        npm run package
    - uses: actions/upload-artifact@v3
      with:
        name: application-dmg
        path: out/**
