name: Build app

on:
  push:
    
jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        mv .env.example .env
        cd src
        cd ui
        npm install
        cd ..
        cd ..
        npm run make:windows
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: out/**/*.exe
