name: Build windows app

on:
  push:
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get .env
      shell: bash
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        curl -H "Authorization: token %REPO_TOKEN%" -H "Accept: application/vnd.github.v3.raw" -o .env -L https://api.github.com/repos/rtr-nettest/open-rmbt-desktop-private/contents/.env.windows-ci
        ls -l
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Build
      shell: bash
      run: |
        pwd
        ls -l
        cd binaries
        # get release of Java engine
        curl -LO https://github.com/rtr-nettest/open-rmbt/releases/download/v0.9/RTR-NetztestCLI-win32.zip
        # unpack
        unzip RTR-NetztestCLI-win32.zip
        mv RTR-Netztest/* RTR-NetztestCLI-linux-x64
        ls -l
        # return to repository root directory
        cd ..
        # check directory again
        pwd

        npm install
        cd src/ui
        npm install
        cd ../..
        npm run make:windows
    - uses: actions/upload-artifact@v4
      with:
        name: application-zip
        path: out/RTR-Netztest-win32-x64/
    - uses: actions/upload-artifact@v4
      with:
        name: application-setup
        path: out/make/squirrel.windows/x64/*.exe
        
    - name: Intermediate file check
      run: |
        cd  out/make
        ls -l
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          out/make

